menu:
  Home: /
  Features: /features.html
  Screenshots: /screenshots.html
  Downloads: /downloads.html
  Documentation: /documents.html
  Translate: /translate.html
  Develop: /develop.html
  About: /about.html
#  Archives: /archives

widgets: 
- recent_posts

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

fancybox: true

google_analytics: UA-34256170-3
rss: /atom.xml
