menu:
  Home: /
  News: /news
  Features: /p/features.html
  Screenshots: /p/screenshots.html
  Downloads: /p/downloads.html
  About: /p/about.html
#  Archives: /archives

widgets: 
- category
- tag

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:
