menu:
  Home: /
  News: /news
  Features: /features
  Screenshots: /screenshots
  Downloads: /downloads
  Translate: /translate
  Develop: /develop
  About: /about
#  Archives: /archives

widgets: 
- recent_posts

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:
